"""Per-trader 'trading personality' analysis + coaching, generated by Claude
from already-computed aggregate stats (session/direction/TP-SL-BE mix,
discipline, notes) — never images, never raw account data."""
from __future__ import annotations

from collections import Counter
from typing import Any, Callable

from anthropic import AsyncAnthropic

from . import config
from .stats import compute

_client: AsyncAnthropic | None = None


def _get_client() -> AsyncAnthropic:
    global _client
    if _client is None:
        _client = AsyncAnthropic(api_key=config.ANTHROPIC_API_KEY)
    return _client


_SYSTEM = (
    "You are an experienced trading coach. Given one trader's aggregate "
    "performance statistics, write a concise, specific analysis of their "
    "trading personality and habits, then concrete ways to improve. Ground "
    "every observation in the numbers given — never invent facts, and if a "
    "figure isn't provided, don't speculate about it. Structure your answer "
    "exactly as:\n"
    "**Trading personality** — 2-4 sentences on their style (e.g. disciplined "
    "vs impulsive, risk appetite, session preference, consistency).\n"
    "**What's working** — 1-2 sentences.\n"
    "**What to improve** — 3-4 short, numbered, specific suggestions tied to "
    "the actual stats (e.g. a weak session, poor SL discipline, a direction "
    "bias, R-multiple sizing).\n"
    "Keep the whole thing under 220 words. Plain language. End with the exact "
    "line 'Not financial advice.'"
)


def _group(trades: list[dict[str, Any]], key_fn: Callable[[dict[str, Any]], str | None]) -> dict[str, dict[str, Any]]:
    out: dict[str, dict[str, Any]] = {}
    for t in trades:
        k = key_fn(t) or "Unknown"
        g = out.setdefault(k, {"n": 0, "pnl": 0.0, "wins": 0, "decisive": 0})
        g["n"] += 1
        if t.get("pnl_amount") is not None:
            g["pnl"] += t["pnl_amount"]
        if t.get("outcome") == "profit":
            g["wins"] += 1
            g["decisive"] += 1
        elif t.get("outcome") == "loss":
            g["decisive"] += 1
    return out


def _fmt_group(groups: dict[str, dict[str, Any]], limit: int = 6) -> str:
    rows = sorted(groups.items(), key=lambda kv: -kv[1]["n"])[:limit]
    if not rows:
        return "(no data)"
    lines = []
    for k, v in rows:
        wr = round(100 * v["wins"] / v["decisive"]) if v["decisive"] else None
        lines.append(f"- {k}: {v['n']} trades, net {v['pnl']:.0f}" + (f", {wr}% win" if wr is not None else ""))
    return "\n".join(lines)


def _discipline_avg(trades: list[dict[str, Any]]) -> str:
    vals: list[float] = []
    for t in trades:
        d = str(t.get("discipline") or "").strip()
        if "/" in d:
            num, _, den = d.partition("/")
            try:
                if float(den):
                    vals.append(float(num) / float(den))
            except ValueError:
                pass
    if not vals:
        return "not tracked"
    return f"{round(100 * sum(vals) / len(vals))}% average (self-rated)"


async def generate(label: str, rows: list[dict[str, Any]]) -> str:
    """`rows` are raw sheet rows already scoped to exactly one trader/account."""
    s = compute(rows)
    trades = s["trades"]

    by_session = _group(trades, lambda t: (str(t.get("session") or "").split("/")[0].strip() or None))
    by_direction = _group(trades, lambda t: (str(t.get("direction") or "").upper() or None))
    by_instrument = _group(trades, lambda t: t.get("instrument") or None)

    outcome_counts = Counter(t.get("outcome") for t in trades)
    total = s["total_trades"] or 1
    tp_pct = round(100 * outcome_counts.get("profit", 0) / total)
    sl_pct = round(100 * outcome_counts.get("loss", 0) / total)
    be_pct = round(100 * outcome_counts.get("breakeven", 0) / total)

    notes = [str(t.get("notes") or "").strip() for t in trades if str(t.get("notes") or "").strip()]
    notes_sample = "\n".join(f"- {n[:160]}" for n in notes[-5:]) if notes else "(none written)"

    user = (
        f"Trader: {label}\n"
        f"Total trades: {s['total_trades']}\n"
        f"Win rate: {s['win_rate']}% ({s['wins']}W / {s['losses']}L / {s['breakeven']}BE)\n"
        f"Outcome mix: Hit TP {tp_pct}% · Hit SL {sl_pct}% · Hit BE {be_pct}%\n"
        f"Net P&L: {s['net_pnl']} · Profit factor: {s['profit_factor']}\n"
        f"Avg win / avg loss: {s['avg_win']} / {s['avg_loss']} · Avg R: {s['avg_r']}\n"
        f"Best trade: {s['best_trade']} · Worst trade: {s['worst_trade']}\n"
        f"Self-rated discipline: {_discipline_avg(trades)}\n\n"
        f"Performance by session:\n{_fmt_group(by_session)}\n\n"
        f"Performance by direction:\n{_fmt_group(by_direction)}\n\n"
        f"Most-traded instruments:\n{_fmt_group(by_instrument)}\n\n"
        f"Recent trade notes (verbatim, may include their own psychology comments):\n{notes_sample}\n\n"
        "Write the trading personality analysis and improvement plan."
    )

    resp = await _get_client().messages.create(
        model=config.ANTHROPIC_MODEL,
        max_tokens=700,
        system=_SYSTEM,
        messages=[{"role": "user", "content": user}],
    )
    return "".join(b.text for b in resp.content if b.type == "text").strip()
